"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const Koa = require("koa");
const bodyParser = require("koa-bodyparser");
const router_1 = require("./router");
require("./blls");
const config = require('config');
const app = new Koa;
app.use(bodyParser());
router_1.default.setRouters(app);
app.listen(config.port);
console.log(`app is listening on ${config.port}`);
